### ISSUE TITLE
message vs data

### ISSUE THREAD

**Issue by Misbah-Ahmad** [hasancse91/Android-Firebase-Notification-With-PHP-Backend#1]
You used two different variables in Push class, $message & $data. What is the difference between them?
Can't we use message variable to contain the data?
@hasancse91

**Comment by hasancse91** [comment]
OK... Let me explain!
Notification has title, message and data payload part. To better understanding check [this image](https://raw.githubusercontent.com/hasancse91/Android-Firebase-Notification/master/data/screen1.png).

First line of notification is title. Then you'll find "Tap to know...". This is the `message` part. And `data` contains the other data payload like image URL, content URL etc.

In a word, `message` is nothing but a plain text which is shown under notification title. On the other hand `data` contains other important data payload.
