### ISSUE TITLE
Notifications not being sent

### ISSUE THREAD

**Issue by jeremy-jamez** [hasancse91/Android-Firebase-Notification-With-PHP-Backend#2]
I've made the changes in config.php but when I enter the information and click send, the response is displayed to the side but my device does not receive the notification. I only receive the notification when using the Firebase Console.

**Comment by benoffi7** [comment]
You should suscribe the device to a topic in Android

`        FirebaseMessaging.getInstance().subscribeToTopic("news");
`

In [dashboard.php](https://github.com/hasancse91/Android-Firebase-Notification-With-PHP-Backend/blob/master/AndroidPushNotification-PHP-Backend/dashboard.php) you change the topic where the notifications go

`$response = $firebase->sendToTopic('news', $json);`

With that and modify the config.php I'm done!
